# Generated by Django 4.2.7 on 2023-12-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=128)),
                ("lastname", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
